services:
  - type: web
    name: analytics-backend
    runtime: node
    buildCommand: cd analytics-backend && npm install && npx nest build
    startCommand: cd analytics-backend && npm run start:prod
