services:
  - type: web
    name: analytics-backend
    runtime: node
    nodeVersion: "18.17.0"
    plan: free
    buildCommand: npm install && npx nest build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_BUILD_MEMORY
        value: 4096
